import { describe, it, expect } from "vitest";
import { assembleCriteriaMarkdown } from "../../src/core/criteriaInit.js";
import { parseCriteria } from "../../src/core/criteria.js";

const base = {
  specPath: "spec.md", generator: "openai:gpt-x",
  projectCriteria: [{ id: "CRIT-PROJECT-TOKEN-EXPIRY", text: "Token expiry uses <=.", optional: false }],
  reqPresent: [] as string[],
  reqCandidates: [{ id: "REQ-AUTH", text: "Auth is required." }]
};

describe("assembleCriteriaMarkdown", () => {
  it("emits the fixed baseline verbatim and the generated project criterion", () => {
    const md = assembleCriteriaMarkdown(base);
    expect(md).toContain("- [CRIT-SCOPE] The design stays within the stated scope and defers non-blockers explicitly.");
    expect(md).toContain("- [CRIT-IMPLEMENTABILITY]");
    expect(md).toContain("- [CRIT-REQ-TAGS]");
    expect(md).toContain("- [CRIT-STYLE OPTIONAL] Terminology is consistent across sections.");
    expect(md).toContain("- [CRIT-PROJECT-TOKEN-EXPIRY] Token expiry uses <=.");
    expect(md).toContain("# Generated by: openai:gpt-x");
    expect(md).toContain("# Generated from: spec.md");
  });

  it("produces markdown that parseCriteria accepts, with REQ lines ignored", () => {
    const md = assembleCriteriaMarkdown(base);
    const { ids } = parseCriteria(md);
    expect(ids).toContain("CRIT-SCOPE");
    expect(ids).toContain("CRIT-PROJECT-TOKEN-EXPIRY");
    expect(ids).not.toContain("REQ-AUTH");   // advisory REQ lines are not criteria
    expect(ids.length).toBe(8);              // 7 baseline + 1 project
  });

  it("shows declared requirements when present and (none found) when absent", () => {
    expect(assembleCriteriaMarkdown({ ...base, reqPresent: ["REQ-X", "REQ-Y"] }))
      .toContain("# spec already declares: REQ-X, REQ-Y");
    expect(assembleCriteriaMarkdown(base)).toContain("# spec already declares: (none found)");
  });

  it("marks an optional project criterion with the OPTIONAL keyword", () => {
    const md = assembleCriteriaMarkdown({
      ...base, projectCriteria: [{ id: "CRIT-PROJECT-STYLE", text: "x", optional: true }]
    });
    expect(md).toContain("- [CRIT-PROJECT-STYLE OPTIONAL] x");
  });
});
