import { parseCriteria } from "./criteria.js";

// Baseline criteria are CODE-OWNED and emitted verbatim so an LLM can never weaken the review
// contract. SCOPE/FEASIBILITY/CORRECTNESS/FAILURE-HANDLING are adapted from examples/criteria.spec.md
// (SCOPE intentionally generalized — the "v1" qualifier dropped — since this baseline is project-
// agnostic); IMPLEMENTABILITY and REQ-TAGS are new baseline criteria owned by this feature; STYLE is
// kept OPTIONAL and ordered last on purpose.
export const BASELINE: string[] = [
  "- [CRIT-SCOPE] The design stays within the stated scope and defers non-blockers explicitly.",
  "- [CRIT-FEASIBILITY] Every claimed guarantee is achievable by the described mechanism.",
  "- [CRIT-CORRECTNESS] No described race, ambiguity, or contradiction can cause wrong behavior.",
  "- [CRIT-FAILURE-HANDLING] Error, retry, and failure paths are specified, not implied.",
  "- [CRIT-IMPLEMENTABILITY] Every step can be built with the described mechanisms; none requires an unavailable capability.",
  "- [CRIT-REQ-TAGS] The spec declares every user-facing requirement as a [REQ-*] tag for downstream plan coverage.",
  "- [CRIT-STYLE OPTIONAL] Terminology is consistent across sections."
];

// Generated project criteria live in their own namespace; the regex both enforces the namespace and
// makes a bare baseline collision (e.g. CRIT-SCOPE) impossible by construction.
export const PROJECT_ID = /^CRIT-PROJECT-[A-Z0-9-]+$/;

export interface ProjectCriterion { id: string; text: string; optional: boolean; }
export interface ReqCandidate { id: string; text: string; }

export function assembleCriteriaMarkdown(a: {
  specPath: string;
  generator: string;
  projectCriteria: ProjectCriterion[];
  reqPresent: string[];
  reqCandidates: ReqCandidate[];
}): string {
  const lines: string[] = [];
  lines.push("# Draft review criteria");
  lines.push(`# Generated by: ${a.generator}`);
  lines.push(`# Generated from: ${a.specPath}`);
  lines.push("# Status: DRAFT — review and edit before use with --criteria.");
  lines.push("");
  lines.push("## Baseline (code-owned — do not weaken)");
  lines.push(...BASELINE);
  lines.push("");
  lines.push("## Project-specific (generated — verify before use)");
  if (a.projectCriteria.length === 0) {
    lines.push("# (none generated)");
  } else {
    for (const c of a.projectCriteria) {
      lines.push(`- [${c.id}${c.optional ? " OPTIONAL" : ""}] ${c.text}`);
    }
  }
  lines.push("");
  lines.push("## Suggested Requirements (advisory — remove or copy into the SPEC before using this file)");
  lines.push("# These are NOT review criteria. Before using this file with --criteria, either:");
  lines.push("#   1. copy the chosen [REQ-*] items into the spec and delete this section, or");
  lines.push("#   2. delete this section if the spec already declares complete [REQ-*] tags.");
  lines.push(`# spec already declares: ${a.reqPresent.length ? a.reqPresent.join(", ") : "(none found)"}`);
  if (a.reqCandidates.length === 0) {
    lines.push("# (no candidates suggested)");
  } else {
    for (const r of a.reqCandidates) lines.push(`- [${r.id}] ${r.text}`);
  }
  lines.push("");
  return lines.join("\n");
}

// A no-op reference so `parseCriteria` is imported here for the generation half (Task 3) to reuse.
void parseCriteria;
